### ISSUE TITLE
App is crashing because of Room cannot verify the data integrity after updating library.

### ISSUE THREAD

**Issue by antanas-radzevicius-tg** [Mopinion-com/mopinion-sdk-android#6]
hey, when trying to update SDK from "1.0.28" to "2.0.1", app is crashing on SDK init. 
IT ONLY HAPPENS WHEN UPDATING THE APP, NOT DOING FRESH INSTALL. 

Suggestion add flag to Room setup where DeploymentDao is - `.fallbackToDestructiveMigration(false)`

Stack trace:
```
java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: bb7bd98e96cb813133ca9aaaa55acba2, found: 1908721fbb8f68e59a2e14ed4584d98f
                                                                                                    	at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.kt:146)
                                                                                                    	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.kt:127)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.kt:287)
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:533)
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:419)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:232)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:190)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
                                                                                                    	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.kt:632)
                                                                                                    	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.kt:451)
                                                                                                    	at androidx.room.RoomDatabase.query(RoomDatabase.kt:480)
                                                                                                    	at androidx.room.util.DBUtil.query(DBUtil.kt:75)
                                                                                                    	at com.mopinion.data.localdb.DeploymentDao_Impl$19.call(DeploymentDao_Impl.java:686)
                                                                                                    	at com.mopinion.data.localdb.DeploymentDao_Impl$19.call(DeploymentDao_Impl.java:682)
                                                                                                    	at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:87)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6af396, Dispatchers.Default]

```

**Comment by Piethot** [comment]
This issue has been resolved in version 2.0.1. https://github.com/Mopinion-com/mopinion-sdk-android/releases/tag/2.0.1

**Comment by Piethot** [comment]
@antanas-radzevicius-tg you mentioned you tried updating to 2.0.1, but still the issue occurs. Can you email us at support@mopinion.com so we can investigate this issue further?

**Comment by andersu** [comment]
I saw the same crash on my first run after updating from 1.0.28 to 2.0.1. 
This is the important part: 
"Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number"

If you only have simple changes in your Room database, you should be able to just update the schema version number.
If not you might need a migration: 
https://developer.android.com/training/data-storage/room/migrating-db-versions

We need this new version for the removal of the READ_MEDIA_IMAGES permission (https://github.com/Mopinion-com/mopinion-sdk-android/issues/5), but we cannot use it if it crashes for all our existing users.

**Comment by ManuelCrovetto** [comment]
@andersu hello, can you please check that your dependencies cache is correctly clean and you are fetching the 2.0.1 version?
Should be in your external dependencies as:

![Image](https://github.com/user-attachments/assets/62f536ab-d5bc-48a8-907a-884593389ab7)

**Comment by andersu** [comment]
@ManuelCrovetto I am sure I did, because it had some breaking changes that I had to fix in the code.

**Comment by andersu** [comment]
I will see if I can reproduce it too

**Comment by ManuelCrovetto** [comment]
@andersu I know the issue was there, but based on your feedback it was fixed by updating the database version.  
The flag of fallBackToDestructiveMigration was already there.
It would be really odd that the issue persists. Anyways let me know if you can reproduce it again please.

**Comment by andersu** [comment]
@ManuelCrovetto 
Sorry, had some other issues to deal with earlier, but I was able to reproduce it now on the first try.

Steps: 
1. Check out an older version of our app using com.mopinion:native-android-sdk:1.0.28
2. Go to a page with a survey (don't know if this step is needed, but just in case): 
![Image](https://github.com/user-attachments/assets/6c76a5ee-7644-4433-af39-5f7a60830437)
3. Upgrade to com.mopinion:native-android-sdk:2.0.1
4. Run the app. Crashes with stacktrace: 
```
Process: nl.debijenkorf, PID: 5175
                                                                                                    java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: bb7bd98e96cb813133ca9aaaa55acba2, found: 1908721fbb8f68e59a2e14ed4584d98f
                                                                                                    	at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.kt:146)
                                                                                                    	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.kt:127)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.kt:287)
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:426)
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:232)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:190)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
                                                                                                    	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.kt:632)
                                                                                                    	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.kt:451)
                                                                                                    	at androidx.room.RoomDatabase.query(RoomDatabase.kt:480)
                                                                                                    	at androidx.room.util.DBUtil.query(DBUtil.kt:75)
                                                                                                    	at com.mopinion.data.localdb.DeploymentDao_Impl$19.call(DeploymentDao_Impl.java:686)
                                                                                                    	at com.mopinion.data.localdb.DeploymentDao_Impl$19.call(DeploymentDao_Impl.java:682)
                                                                                                    	at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:87)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by ManuelCrovetto** [comment]
@andersu I followed exactly the steps, actually created 3 branches for this. These are the steps I followed, always cleaning cache and double checking the dependencies are correctly refreshed:

Environment 1:
1. I have set Mopinion app with `implementation 'com.github.Mopinion-com:native-android-sdk:1.0.28'`.
2. Build and running.
3. Then updated the Mopinion dependency to implementation `'com.github.Mopinion-com.native-android-sdk:mopinion-sdk:2.0.0'`.
4. Indeed it crashes due with `IllegalStateException: Room cannot verify the data integrity.`

Environment 2: 
1. I have set Mopinion app with `implementation 'com.github.Mopinion-com:native-android-sdk:1.0.28'`.
2. Build and running.
3. Then updated the Mopinion dependency to implementation `'com.github.Mopinion-com.native-android-sdk:mopinion-sdk:2.0.1'`.
4. There is no crash.

In your reproduction steps, on step number 3 there is something that causes me confusion, you say you are upgrading to `com.mopinion:native-android-sdk:2.0.1`. I guess it's a typo, the correct dependency would be `com.mopinion:native-android-sdk:mopinion-sdk:2.0.1'`. 
Can you please confirm it is a typo?

**Comment by ManuelCrovetto** [comment]
@andersu I see, if you use `com.mopinion:native-android-sdk:2.0.1` it will serve you all the modules and for some reason it doesn't serve you the updated one.
Also, if you use `'com.mopinion.native-android-sdk:mopinion-sdk:2.0.1'` it will serve you the single mopinion-sdk full version module but it is not the latest one.

**Please, use `'com.github.Mopinion-com.native-android-sdk:mopinion-sdk:2.0.1'`, I see with this route, the correct module is served. I will update the readme until I find why Jitpack is doing this.**

**Comment by ManuelCrovetto** [comment]
@andersu I have reported this issue to Jitpack. 

https://github.com/jitpack/jitpack.io/issues/6814

**Comment by andersu** [comment]
@ManuelCrovetto Odd indeed. This project had that wrong/whole group dependency since before my time, I see.
 
I have changed to `com.github.Mopinion-com.native-android-sdk:mopinion-sdk:2.0.1` and tried again to reproduce, with no crash this time. Thanks!

**Comment by andersu** [comment]
@ManuelCrovetto Unfortunately I now get another crash when opening the feedback screen. But I am not sure what is causing it. It might not be Mopinion at all. I have had some similar issues lately so I filed a bug here: 
https://issuetracker.google.com/issues/390736538

I notice that both our app and your library use koin, so wondering if something is not working together well there.
Please let me know if you have any ideas.

**Comment by ManuelCrovetto** [comment]
@andersu We started to use Koin in 2.0.0, but we isolate its context through [**Koin Context Isolation**](https://insert-koin.io/docs/reference/koin-core/context-isolation/). If you could run the SDK, trigger some forms and it was working, should not be Koin related.
The error you should get in that case must be a `KoinAppAlreadyStartedException`. In the bug you reported I don't see such an exception.
Anyways I will be researching about it. Please if you dive deeper into the issue and determine it is related to the Mopinion SDK, open a new issue. I will close this one by the moment.

**Comment by ManuelCrovetto** [comment]
> [@andersu](https://github.com/andersu) We started to use Koin in 2.0.0, but we isolate its context through [**Koin Context Isolation**](https://insert-koin.io/docs/reference/koin-core/context-isolation/). If you could run the SDK, trigger some forms and it was working, should not be Koin related. The error you should get in that case must be a `KoinAppAlreadyStartedException`. In the bug you reported I don't see such an exception. Anyways I will be researching about it. Please if you dive deeper into the issue and determine it is related to the Mopinion SDK, open a new issue. I will close this one by the moment.

@andersu ℹ️ just as extra info: I just migrated our App from Hilt to Koin to see if our Koin context my be causing some issues with the App Koin Context and **I am not having any issues**, the SDK runs well con the app.
